import { Property } from '@/types/property';

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-osasco-3464',
    titulo: 'Residencial Continental',
    urlAnuncio: 'https://www.b2mimoveis.com.br/imovel/apartamento-osasco-3-quartos-84-m/AP3464-B2MC',
    urlImagem: 'https://imgs.kenlo.io/VWRCUkQ2Tnp3d1BJRDBJVe1szkhnWr9UfpZS9ftWwjXgr7v5Znen3XVcMHllDVRJJeIbi3YwVYEtu2JbwsxMo08BqtsDUISG7SC6wYm9oufJhx6X16nYlp3jzcXtYuzAxMU0lICrAniXrZZVQ-gXbGJpYutAazy3R8KRGXtS-BeQ-X7iUaRiE3Jb4zEMgUl0+2f8fqWT7nIM-Qr1BOL1uAeIRb7hP0FTQPlLANk18QdW9hinR0InpwcS45urs3PTcKG1MI36iGwAF0wy6oK5APevm5PPedV-GacxP3wP61NeW6wcmvuVAupw6QEZovrFTQeShQjQiOM3eYWuWN1JlbwAlAvAH7UfuRvtwtKU0qP5akmDZlc0obzO8PvlPP7xTbSkZ26pkpg85ZjVEMhUN46nSDQVFyQvcXdBsl7ktPyL7AD5bSnYrhAWHxPRzsM49G5-clU=.jpg',
    bairro: 'Vila Yara / Continental - Osasco',
    endereco: 'Avenida Yara - Próximo ao Continental Shopping',
    valorAluguel: 4300,
    valorCondominio: 820,
    valorIptu: 210,
    custoTotalMensal: 5330,
    dormitorios: 3,
    suites: 1,
    banheiros: 2,
    vagasGaragem: 2,
    areaUtil: 84,
    precoMetroQuadrado: 63.4,
    tempoAteTrabalhoMinutos: 25,
    tempoSaymonMinutos: 20,
    tempoKellyMinutos: 30,
    distanciaMetroKm: 2.1,
    diferenciais: [
      'Varanda Gourmet',
      'Armários Planejados',
      'Piscina',
      'Academia',
      'Churrasqueira',
      'Salão de Festas',
      'Portaria 24h / Blindada',
      'Sol da Manhã',
      'Aceita Pet',
    ],
    status: 'Para Analisar',

    // Avaliação Saymon
    notaSaymon: 0,
    vereditoSaymon: undefined,
    opiniaoSaymon: undefined,

    // Avaliação Kelly
    notaKelly: 0,
    vereditoKelly: undefined,
    opiniaoKelly: undefined,

    mediaCasal: 0,
    notaPessoal: 0,

    observacoes: 'Código AP3464-B2MC. Agendar visita presencial para conferir a vista e o sol da manhã.',
    duvidasCorretor: '1. A vaga de garagem é livre ou presa?\n2. O valor do condomínio inclui água/gás?\n3. Aceita seguro fiança?',
    dataCadastro: '2026-08-16T14:00:00.000Z',
    isFavorito: false,
  },
  {
    id: 'prop-vanderleia-78804346',
    titulo: 'Edifício Deputado Emílio Carlos',
    urlAnuncio: 'http://www.vanderleiaimoveis.com.br/alugar/sp/osasco/vila-yara/apartamento/78804346',
    urlImagem: 'https://cdn5.uso.com.br/48599/2026/08/315297296.jpg',
    bairro: 'Vila Yara - Osasco',
    endereco: 'Rua Deputado Emílio Carlos, Vila Yara',
    valorAluguel: 3800,
    valorCondominio: 829,
    valorIptu: 220,
    custoTotalMensal: 4849,
    dormitorios: 3,
    suites: 1,
    banheiros: 2,
    vagasGaragem: 2,
    areaUtil: 75,
    precoMetroQuadrado: 64.7,
    tempoAteTrabalhoMinutos: 24,
    distanciaMetroKm: 2.0,
    diferenciais: [
      'Varanda / Sacada',
      'Armários Planejados',
      'Piscina',
      'Academia',
      'Salão de Festas',
      'Portaria 24h / Blindada',
      'Elevador',
      'Aceita Pet',
    ],
    status: 'Para Analisar',

    // Avaliação Saymon
    notaSaymon: 0,
    vereditoSaymon: undefined,
    opiniaoSaymon: undefined,

    // Avaliação Kelly
    notaKelly: 0,
    vereditoKelly: undefined,
    opiniaoKelly: undefined,

    mediaCasal: 0,
    notaPessoal: 0,

    observacoes: 'Código AP00770 - Vanderleia Imóveis (Tel/Whats: 11 99487-8624). Total mensal R$ 4.849.',
    duvidasCorretor: '1. As duas vagas são cobertas e demarcadas?\n2. Tem ar-condicionado na suíte?\n3. O andar é alto?',
    dataCadastro: '2026-08-17T14:30:00.000Z',
    isFavorito: false,
  },
  {
    id: 'prop-osasco-3527',
    titulo: 'Lorian Moema',
    urlAnuncio: 'http://b2mimoveis.com.br/imovel/detalhes/AP3527-B2MC',
    urlImagem: 'https://imgs.kenlo.io/VWRCUkQ2Tnp3d1BJRDBJVe1szkhnWr9UfpZS9ftWwjXgr7v5Znen3XVcMHllDVRJJeIbi3YwVYEtu0w8if1+1k83w8MHZ5uShCi-w4O07s+BpVy336uHg+Pf+IbDBeOGkosy2qf8FlTp77dLf9wWI2t4SrlhGB3EVqygJnlqrXyvo3XnEYp4UWla3iE3vkoJymuacciF1nU78SOdEsvKlw6MToqjDWcEHrMNAdsz6EIJ9xa9SUxy8h8d4563vSCAaKyyLIOvkiMYDwYu6oa6SeKv15TFJsonDqooL34J41sRFqAe2beFX6J24QkLuOfUB1+EkBnHl+8kYMGwX9hLnaoclAzHGLZJu02+kICR1-OqOkiCNgY5-Oybqfq4aP7yG-zscXuqhYsCyY7dIvVZKpiiDCMXAjMleGNWuUm6qvXO4g6rcjWJtghHCVTfwI4npnZ9ehhc.jpg',
    bairro: 'Vila Yara - Osasco',
    endereco: 'Rua Moema - Vila Yara',
    valorAluguel: 2800,
    valorCondominio: 950,
    valorIptu: 238,
    custoTotalMensal: 3988,
    dormitorios: 3,
    suites: 1,
    banheiros: 2,
    vagasGaragem: 2,
    areaUtil: 90,
    precoMetroQuadrado: 44.3,
    tempoAteTrabalhoMinutos: 25,
    distanciaMetroKm: 2.2,
    diferenciais: [
      'Varanda / Sacada',
      'Armários Planejados',
      'Piscina',
      'Academia',
      'Quadra de Tênis / Poliesportiva',
      'Portaria 24h / Blindada',
      'Vista Livre',
      'Andar Alto',
    ],
    status: 'Para Analisar',

    // Avaliação Saymon
    notaSaymon: 0,
    vereditoSaymon: undefined,
    opiniaoSaymon: undefined,

    // Avaliação Kelly
    notaKelly: 0,
    vereditoKelly: undefined,
    opiniaoKelly: undefined,

    mediaCasal: 0,
    notaPessoal: 0,

    observacoes: 'Código AP3527-B2MC. Pacote fechado divulgado por R$ 3.988,00/mês.',
    duvidasCorretor: '1. O apartamento pega o sol da manhã?\n2. As chaves já estão na imobiliária?',
    dataCadastro: '2026-08-16T15:30:00.000Z',
    isFavorito: false,
  },
  {
    id: 'prop-vilasaofrancisco-viva',
    titulo: 'Residencial Cândido Mota',
    urlAnuncio: 'https://www.vivareal.com.br/imovel/apartamento-3-quartos-vila-sao-francisco-zona-oeste-zona-oeste-sao-paulo-com-garagem-80m2-aluguel-RS3800-id-2904724653/',
    urlImagem: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    bairro: 'Vila São Francisco - Zona Oeste SP',
    endereco: 'Rua Cândido Mota Filho, Vila São Francisco',
    valorAluguel: 3800,
    valorCondominio: 790,
    valorIptu: 180,
    custoTotalMensal: 4770,
    dormitorios: 3,
    suites: 1,
    banheiros: 2,
    vagasGaragem: 1,
    areaUtil: 80,
    precoMetroQuadrado: 59.6,
    tempoAteTrabalhoMinutos: 22,
    distanciaMetroKm: 1.8,
    diferenciais: [
      'Varanda / Sacada',
      'Armários Planejados',
      'Piscina',
      'Salão de Festas',
      'Aceita Pet',
      'Portaria 24h / Blindada',
      'Próximo a Parques / Shoppings',
      'Elevador',
    ],
    status: 'Para Analisar',

    // Avaliação Saymon
    notaSaymon: 0,
    vereditoSaymon: undefined,
    opiniaoSaymon: undefined,

    // Avaliação Kelly
    notaKelly: 0,
    vereditoKelly: undefined,
    opiniaoKelly: undefined,

    mediaCasal: 0,
    notaPessoal: 0,

    observacoes: 'VivaReal ID 2904724653. Checar se a vaga de garagem é livre ou presa.',
    duvidasCorretor: '1. A vaga de garagem é livre ou trancada?\n2. Aceita pet de médio porte?',
    dataCadastro: '2026-08-16T17:00:00.000Z',
    isFavorito: false,
  },
  {
    id: 'prop-vilayara-viva-75m',
    titulo: 'Edifício Parque Vila Yara',
    urlAnuncio: 'https://www.vivareal.com.br/imovel/apartamento-3-quartos-vila-yara-bairros-osasco-com-garagem-75m2-aluguel-RS3800-id-2903669398/',
    urlImagem: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80',
    bairro: 'Vila Yara - Osasco',
    endereco: 'Rua Deputado Emílio Carlos / Vila Yara',
    valorAluguel: 3800,
    valorCondominio: 750,
    valorIptu: 190,
    custoTotalMensal: 4740,
    dormitorios: 3,
    suites: 1,
    banheiros: 2,
    vagasGaragem: 1,
    areaUtil: 75,
    precoMetroQuadrado: 63.2,
    tempoAteTrabalhoMinutos: 24,
    distanciaMetroKm: 2.0,
    diferenciais: [
      'Varanda / Sacada',
      'Armários Planejados',
      'Piscina',
      'Academia',
      'Salão de Festas',
      'Portaria 24h / Blindada',
      'Elevador',
      'Aceita Pet',
    ],
    status: 'Para Analisar',

    // Avaliação Saymon
    notaSaymon: 0,
    vereditoSaymon: undefined,
    opiniaoSaymon: undefined,

    // Avaliação Kelly
    notaKelly: 0,
    vereditoKelly: undefined,
    opiniaoKelly: undefined,

    mediaCasal: 0,
    notaPessoal: 0,

    observacoes: 'VivaReal ID 2903669398. Comparar com o de 84m² da Vila Yara que tem 2 vagas de garagem.',
    duvidasCorretor: '1. O apartamento possui armários em todos os 3 quartos?\n2. O condomínio tem gerador para o elevador?',
    dataCadastro: '2026-08-17T10:00:00.000Z',
    isFavorito: false,
  },
  {
    id: 'prop-adalgisa-viva-82m',
    titulo: 'Residencial Adalgisa',
    urlAnuncio: 'https://www.vivareal.com.br/imovel/apartamento-3-quartos-adalgisa-bairros-osasco-com-garagem-82m2-aluguel-RS4800-id-2900150006/',
    urlImagem: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    bairro: 'Adalgisa - Osasco',
    endereco: 'Bairro Adalgisa - Osasco',
    valorAluguel: 4800,
    valorCondominio: 850,
    valorIptu: 220,
    custoTotalMensal: 5870,
    dormitorios: 3,
    suites: 1,
    banheiros: 2,
    vagasGaragem: 1,
    areaUtil: 82,
    precoMetroQuadrado: 71.5,
    tempoAteTrabalhoMinutos: 20,
    tempoSaymonMinutos: 15,
    tempoKellyMinutos: 25,
    distanciaMetroKm: 1.5,
    diferenciais: [
      'Varanda / Sacada',
      'Armários Planejados',
      'Piscina',
      'Academia',
      'Salão de Festas',
      'Portaria 24h / Blindada',
      'Elevador',
      'Aceita Pet',
    ],
    status: 'Para Analisar',

    // Avaliação Saymon
    notaSaymon: 0,
    vereditoSaymon: undefined,
    opiniaoSaymon: undefined,

    // Avaliação Kelly
    notaKelly: 0,
    vereditoKelly: undefined,
    opiniaoKelly: undefined,

    mediaCasal: 0,
    notaPessoal: 0,

    observacoes: 'VivaReal ID 2900150006. 82m², 3 quartos em Adalgisa.',
    duvidasCorretor: '1. O valor do condomínio inclui água ou gás?\n2. A vaga de garagem é coberta e livre?',
    dataCadastro: '2026-08-20T22:00:00.000Z',
    isFavorito: false,
  },
];
